### PR TITLE
Clozure cl fix

### PR DESCRIPTION
**Pull request by guicho271828**
- first run of the test pass and rest fails (on clozure cl)
- NNS on R*-tree fails on ccl. the test case is removed
- related to #4

### CODE REVIEW

**Comment by rpav** [comment]
Ah looks good thanks.  Any idea why R\* fails on CCL?

**Comment by guicho271828** [comment]
The problem exists in the library itself I guess, not in the test. (both on sbcl and ccl)
The minimal code to reproduce the error is shown below.
However, in order to reproduce the error you will have to run it **several times** because _it depends on the input data._
Thanks to the exhaustive random testing, we get to know about this bug.

``` lisp
(require :spatial-trees.test) ;; the test will fail

;; after the load has been completed,
(in-package :spatial-trees-test) ; ouch, this is not renamed yet

;; then run below several times ... 5 times or so may be enough
(loop for kind in '(:r :greene :r* :x)
   do (loop repeat 100
         for list = (loop repeat 200 collect (make-random-rectangle))
         do (let ((tree (make-spatial-tree kind :rectfun #'identity)))
              (dolist (r list)
                (insert r tree))))) ;; <--- just inserting a rectangle, but it *sometimes* signals an error
```

**Comment by guicho271828** [comment]
or maybe due to the change I made. I will track down the error...

**Comment by guicho271828** [comment]
Confirmed.
Reproduced in ccl, in commit b9f6f3caf9e0a526b8bbe4de27510045d30c2db9 .
I was not involved at that time.
so this is a problem in the library itself.

**Comment by guicho271828** [comment]
There are two kinds of error.
First one is signalled from (HEIGHT #<R_-TREE ...)) .
Second one is this (also related to R_-tree):

```
 There is no applicable method for the generic function:
  #<STANDARD-GENERIC-FUNCTION (SETF PARENT) #x18C283D6>
when called with arguments:
  (#<SPATIAL-TREE-NODE #<(0.42134553,0.061936513) - (1.3773994,0.8995452)> ... #10)
   [Condition of type CCL:NO-APPLICABLE-METHOD-EXISTS]

  0: (#<CCL::STANDARD-KERNEL-METHOD NO-APPLICABLE-METHOD (T)> #<STANDARD-GENERIC-FUNCTION (SETF PARENT) #x18C283D6> #<SPATIAL-TREE-NODE #<(0.42134553,0.061936513) - (1.3773994,0.8995452)> (#<SPATIAL-TREE-L..
  1: (NIL #<Unknown Arguments>)
  2: (#<STANDARD-METHOD ADJUST-TREE (R-TREE T)> #<R*-TREE #<SPATIAL-TREE-NODE (#<SPATIAL-TREE-NODE #<(0.0087614525,0.0014770869) - (1.1816769,1.6085284)> ..)))) #<SPATIAL-TREE-LEAF-NODE #<(0.42134553,0.061..
  3: (%INSERT #S(LEAF-NODE-ENTRY :RECTANGLE #<(0.615465,0.15804224) - (1.2664554,0.24819304)> :DATUM #<(0.615465,0.15804224) - (1.2664554,0.24819304)>) #<R*-TREE #<SPATIAL-TREE-NODE (#<SPATIAL-TREE-NODE #<..
  4: (REINSERT #S(LEAF-NODE-ENTRY :RECTANGLE #<(0.8815057,0.1985789) - (1.3660911,0.67779934)> :DATUM #<(0.8815057,0.1985789) - (1.3660911,0.67779934)>) #<R*-TREE #<SPATIAL-TREE-NODE (#<SPATIAL-TREE-NODE #..
  5: (OVERFLOW-TREATMENT #S(LEAF-NODE-ENTRY :RECTANGLE #<(0.8815057,0.1985789) - (1.3660911,0.67779934)> :DATUM #<(0.8815057,0.1985789) - (1.3660911,0.67779934)>) #<R*-TREE #<SPATIAL-TREE-NODE (#<SPATIAL-T..
  6: (%INSERT #S(LEAF-NODE-ENTRY :RECTANGLE #<(0.8815057,0.1985789) - (1.3660911,0.67779934)> :DATUM #<(0.8815057,0.1985789) - (1.3660911,0.67779934)>) #<R*-TREE #<SPATIAL-TREE-NODE (#<SPATIAL-TREE-NODE #<..
  7: (#<STANDARD-METHOD INSERT (T R*-TREE)> #<(0.8815057,0.1985789) - (1.3660911,0.67779934)> #<R*-TREE #<SPATIAL-TREE-NODE (#<SPATIAL-TREE-NODE #<(0.0087614525,0.0014770869) - (1.1816769,1.6085284)> ..)))..
```

**Comment by guicho271828** [comment]
I guess the current state of the master branch will not be included into the quicklisp until the problem is fixed
because the test currently does not pass.

**Pull request merged**
