### PR TITLE
optimize intersectp

### PR DESCRIPTION
**Pull request by hanshuebner**
This  patch removes the unnecessary consing in intersectp, which noticeably speeds up lookups in our application.

### CODE REVIEW

**Comment by rpav** [comment]
Does performance look similar if you use `EVERY` on a non-consing variant of `%INTERSECT/1D` (possibly with inlining), such as:

``` lisp
(declaim (inline %intersect/1d-p))
(defun %intersect/1d-p (l1 h1 l2 h2)
  (or (and (bound<= l1 l2) (bound<= l2 h1))
      (and (bound<= l2 l1) (bound<= l1 h2))))
```

If `LOOP` is still significantly faster, it would be preferable to split this out, at least.

**Comment by hanshuebner** [comment]
Please note that each call to every will cons up the argument list.  Even if this is just ephemeral garbage that will be collected quickly, it adds to the runtime.

**Comment by rpav** [comment]
Well, `LOOP` should be fine in this case, just split the test into a separate function as above.

**Comment by rpav** [comment]
Er, doh.  Merged.

**Pull request merged**
